name: Test macOS

on:
  workflow_dispatch:  # This allows manual triggering

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test on macOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: macos-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose
      env:
        COMMAND_VAULT_TEST: 1
